import type { GameState } from '../../src/types/game'

// GENERATED by `npm run print-monopoly-rent-seed` — do not edit by hand.
// Alpha owns the full Dark Blue set (37 + 39); Bravo owes $100 on Boardwalk (base $50 x2).
export const monopolyRentSeed: GameState = {
  "phase": "resolving",
  "players": [
    {
      "id": 0,
      "name": "Alpha",
      "money": 1000,
      "position": 0,
      "properties": [
        37,
        39
      ],
      "passedGo": true,
      "inJail": false,
      "jailTurns": 0,
      "bankrupt": false,
      "getOutOfJailFreeCards": 0,
      "isBot": false,
      "botControlled": false,
      "afk": false,
      "color": "#E74C3C",
      "avatar": {
        "kind": "preset",
        "id": "cat"
      }
    },
    {
      "id": 1,
      "name": "Bravo",
      "money": 1500,
      "position": 0,
      "properties": [],
      "passedGo": true,
      "inJail": false,
      "jailTurns": 0,
      "bankrupt": false,
      "getOutOfJailFreeCards": 0,
      "isBot": false,
      "botControlled": false,
      "afk": false,
      "color": "#3498DB",
      "avatar": {
        "kind": "preset",
        "id": "cat"
      }
    }
  ],
  "turnOrder": [
    1,
    0
  ],
  "currentPlayer": 1,
  "board": [
    {
      "id": 0,
      "type": "go",
      "owner": null,
      "houses": 0,
      "mortgaged": false
    },
    {
      "id": 1,
      "type": "property",
      "price": 60,
      "rent": [
        2,
        10,
        30,
        90,
        160,
        250
      ],
      "houseCost": [
        25,
        50,
        75,
        100,
        150
      ],
      "color": "#8B4513",
      "owner": null,
      "houses": 0,
      "mortgaged": false
    },
    {
      "id": 2,
      "type": "community",
      "owner": null,
      "houses": 0,
      "mortgaged": false
    },
    {
      "id": 3,
      "type": "property",
      "price": 60,
      "rent": [
        4,
        20,
        60,
        180,
        320,
        450
      ],
      "houseCost": [
        25,
        50,
        75,
        100,
        150
      ],
      "color": "#8B4513",
      "owner": null,
      "houses": 0,
      "mortgaged": false
    },
    {
      "id": 4,
      "type": "tax",
      "owner": null,
      "houses": 0,
      "mortgaged": false,
      "taxType": "income"
    },
    {
      "id": 5,
      "type": "railroad",
      "price": 200,
      "rent": [
        25,
        50,
        100,
        200
      ],
      "owner": null,
      "houses": 0,
      "mortgaged": false
    },
    {
      "id": 6,
      "type": "property",
      "price": 100,
      "rent": [
        6,
        30,
        90,
        270,
        400,
        550
      ],
      "houseCost": [
        25,
        50,
        75,
        100,
        150
      ],
      "color": "#87CEEB",
      "owner": null,
      "houses": 0,
      "mortgaged": false
    },
    {
      "id": 7,
      "type": "chance",
      "owner": null,
      "houses": 0,
      "mortgaged": false
    },
    {
      "id": 8,
      "type": "property",
      "price": 100,
      "rent": [
        6,
        30,
        90,
        270,
        400,
        550
      ],
      "houseCost": [
        25,
        50,
        75,
        100,
        150
      ],
      "color": "#87CEEB",
      "owner": null,
      "houses": 0,
      "mortgaged": false
    },
    {
      "id": 9,
      "type": "property",
      "price": 120,
      "rent": [
        8,
        40,
        100,
        300,
        450,
        600
      ],
      "houseCost": [
        25,
        50,
        75,
        100,
        150
      ],
      "color": "#87CEEB",
      "owner": null,
      "houses": 0,
      "mortgaged": false
    },
    {
      "id": 10,
      "type": "jail",
      "owner": null,
      "houses": 0,
      "mortgaged": false
    },
    {
      "id": 11,
      "type": "property",
      "price": 140,
      "rent": [
        10,
        50,
        150,
        450,
        625,
        750
      ],
      "houseCost": [
        50,
        100,
        150,
        200,
        250
      ],
      "color": "#FF69B4",
      "owner": null,
      "houses": 0,
      "mortgaged": false
    },
    {
      "id": 12,
      "type": "utility",
      "price": 150,
      "owner": null,
      "houses": 0,
      "mortgaged": false
    },
    {
      "id": 13,
      "type": "property",
      "price": 140,
      "rent": [
        10,
        50,
        150,
        450,
        625,
        750
      ],
      "houseCost": [
        50,
        100,
        150,
        200,
        250
      ],
      "color": "#FF69B4",
      "owner": null,
      "houses": 0,
      "mortgaged": false
    },
    {
      "id": 14,
      "type": "property",
      "price": 160,
      "rent": [
        12,
        60,
        180,
        500,
        700,
        900
      ],
      "houseCost": [
        50,
        100,
        150,
        200,
        250
      ],
      "color": "#FF69B4",
      "owner": null,
      "houses": 0,
      "mortgaged": false
    },
    {
      "id": 15,
      "type": "railroad",
      "price": 200,
      "rent": [
        25,
        50,
        100,
        200
      ],
      "owner": null,
      "houses": 0,
      "mortgaged": false
    },
    {
      "id": 16,
      "type": "property",
      "price": 180,
      "rent": [
        14,
        70,
        200,
        550,
        750,
        950
      ],
      "houseCost": [
        50,
        100,
        150,
        200,
        250
      ],
      "color": "#FFA500",
      "owner": null,
      "houses": 0,
      "mortgaged": false
    },
    {
      "id": 17,
      "type": "community",
      "owner": null,
      "houses": 0,
      "mortgaged": false
    },
    {
      "id": 18,
      "type": "property",
      "price": 180,
      "rent": [
        14,
        70,
        200,
        550,
        750,
        950
      ],
      "houseCost": [
        50,
        100,
        150,
        200,
        250
      ],
      "color": "#FFA500",
      "owner": null,
      "houses": 0,
      "mortgaged": false
    },
    {
      "id": 19,
      "type": "property",
      "price": 200,
      "rent": [
        16,
        80,
        220,
        600,
        800,
        1000
      ],
      "houseCost": [
        50,
        100,
        150,
        200,
        250
      ],
      "color": "#FFA500",
      "owner": null,
      "houses": 0,
      "mortgaged": false
    },
    {
      "id": 20,
      "type": "freeParking",
      "owner": null,
      "houses": 0,
      "mortgaged": false
    },
    {
      "id": 21,
      "type": "property",
      "price": 220,
      "rent": [
        18,
        90,
        250,
        700,
        875,
        1050
      ],
      "houseCost": [
        75,
        150,
        225,
        300,
        375
      ],
      "color": "#FF0000",
      "owner": null,
      "houses": 0,
      "mortgaged": false
    },
    {
      "id": 22,
      "type": "chance",
      "owner": null,
      "houses": 0,
      "mortgaged": false
    },
    {
      "id": 23,
      "type": "property",
      "price": 220,
      "rent": [
        18,
        90,
        250,
        700,
        875,
        1050
      ],
      "houseCost": [
        75,
        150,
        225,
        300,
        375
      ],
      "color": "#FF0000",
      "owner": null,
      "houses": 0,
      "mortgaged": false
    },
    {
      "id": 24,
      "type": "property",
      "price": 240,
      "rent": [
        20,
        100,
        300,
        750,
        925,
        1100
      ],
      "houseCost": [
        75,
        150,
        225,
        300,
        375
      ],
      "color": "#FF0000",
      "owner": null,
      "houses": 0,
      "mortgaged": false
    },
    {
      "id": 25,
      "type": "railroad",
      "price": 200,
      "rent": [
        25,
        50,
        100,
        200
      ],
      "owner": null,
      "houses": 0,
      "mortgaged": false
    },
    {
      "id": 26,
      "type": "property",
      "price": 260,
      "rent": [
        22,
        110,
        330,
        800,
        975,
        1150
      ],
      "houseCost": [
        75,
        150,
        225,
        300,
        375
      ],
      "color": "#FFFF00",
      "owner": null,
      "houses": 0,
      "mortgaged": false
    },
    {
      "id": 27,
      "type": "property",
      "price": 260,
      "rent": [
        22,
        110,
        330,
        800,
        975,
        1150
      ],
      "houseCost": [
        75,
        150,
        225,
        300,
        375
      ],
      "color": "#FFFF00",
      "owner": null,
      "houses": 0,
      "mortgaged": false
    },
    {
      "id": 28,
      "type": "utility",
      "price": 150,
      "owner": null,
      "houses": 0,
      "mortgaged": false
    },
    {
      "id": 29,
      "type": "property",
      "price": 280,
      "rent": [
        24,
        120,
        360,
        850,
        1025,
        1200
      ],
      "houseCost": [
        75,
        150,
        225,
        300,
        375
      ],
      "color": "#FFFF00",
      "owner": null,
      "houses": 0,
      "mortgaged": false
    },
    {
      "id": 30,
      "type": "goToJail",
      "owner": null,
      "houses": 0,
      "mortgaged": false
    },
    {
      "id": 31,
      "type": "property",
      "price": 300,
      "rent": [
        26,
        130,
        390,
        900,
        1100,
        1275
      ],
      "houseCost": [
        100,
        200,
        300,
        400,
        500
      ],
      "color": "#008000",
      "owner": null,
      "houses": 0,
      "mortgaged": false
    },
    {
      "id": 32,
      "type": "property",
      "price": 300,
      "rent": [
        26,
        130,
        390,
        900,
        1100,
        1275
      ],
      "houseCost": [
        100,
        200,
        300,
        400,
        500
      ],
      "color": "#008000",
      "owner": null,
      "houses": 0,
      "mortgaged": false
    },
    {
      "id": 33,
      "type": "community",
      "owner": null,
      "houses": 0,
      "mortgaged": false
    },
    {
      "id": 34,
      "type": "property",
      "price": 320,
      "rent": [
        28,
        150,
        450,
        1000,
        1200,
        1400
      ],
      "houseCost": [
        100,
        200,
        300,
        400,
        500
      ],
      "color": "#008000",
      "owner": null,
      "houses": 0,
      "mortgaged": false
    },
    {
      "id": 35,
      "type": "railroad",
      "price": 200,
      "rent": [
        25,
        50,
        100,
        200
      ],
      "owner": null,
      "houses": 0,
      "mortgaged": false
    },
    {
      "id": 36,
      "type": "chance",
      "owner": null,
      "houses": 0,
      "mortgaged": false
    },
    {
      "id": 37,
      "type": "property",
      "price": 350,
      "rent": [
        35,
        175,
        500,
        1100,
        1300,
        1500
      ],
      "houseCost": [
        100,
        200,
        300,
        400,
        500
      ],
      "color": "#00008B",
      "owner": 0,
      "houses": 0,
      "mortgaged": false
    },
    {
      "id": 38,
      "type": "tax",
      "price": 100,
      "owner": null,
      "houses": 0,
      "mortgaged": false,
      "taxType": "luxury"
    },
    {
      "id": 39,
      "type": "property",
      "price": 400,
      "rent": [
        50,
        200,
        600,
        1400,
        1700,
        2000
      ],
      "houseCost": [
        100,
        200,
        300,
        400,
        500
      ],
      "color": "#00008B",
      "owner": 0,
      "houses": 0,
      "mortgaged": false
    }
  ],
  "chanceDeck": [
    {
      "id": 1,
      "type": "chance",
      "effect": {
        "action": "goToSpace",
        "spaceId": 0
      }
    },
    {
      "id": 2,
      "type": "chance",
      "effect": {
        "action": "goToSpace",
        "spaceId": 37
      }
    },
    {
      "id": 3,
      "type": "chance",
      "effect": {
        "action": "goToSpace",
        "spaceId": 39
      }
    },
    {
      "id": 4,
      "type": "chance",
      "effect": {
        "action": "goToSpace",
        "spaceId": 5
      }
    },
    {
      "id": 5,
      "type": "chance",
      "effect": {
        "action": "collect",
        "amount": 50
      }
    },
    {
      "id": 6,
      "type": "chance",
      "effect": {
        "action": "goToJail"
      }
    },
    {
      "id": 7,
      "type": "chance",
      "effect": {
        "action": "getOutOfJailFree"
      }
    },
    {
      "id": 8,
      "type": "chance",
      "effect": {
        "action": "streetRepairs",
        "perHouse": 25,
        "perHotel": 100
      }
    },
    {
      "id": 9,
      "type": "chance",
      "effect": {
        "action": "collectFromPlayers",
        "amount": 10
      }
    },
    {
      "id": 10,
      "type": "chance",
      "effect": {
        "action": "goToSpace",
        "spaceId": -3
      }
    }
  ],
  "communityDeck": [
    {
      "id": 101,
      "type": "community",
      "effect": {
        "action": "collect",
        "amount": 200
      }
    },
    {
      "id": 102,
      "type": "community",
      "effect": {
        "action": "pay",
        "amount": 100
      }
    },
    {
      "id": 103,
      "type": "community",
      "effect": {
        "action": "pay",
        "amount": 50
      }
    },
    {
      "id": 104,
      "type": "community",
      "effect": {
        "action": "getOutOfJailFree"
      }
    },
    {
      "id": 105,
      "type": "community",
      "effect": {
        "action": "goToJail"
      }
    },
    {
      "id": 106,
      "type": "community",
      "effect": {
        "action": "collect",
        "amount": 100
      }
    },
    {
      "id": 107,
      "type": "community",
      "effect": {
        "action": "collect",
        "amount": 100
      }
    },
    {
      "id": 108,
      "type": "community",
      "effect": {
        "action": "collect",
        "amount": 50
      }
    },
    {
      "id": 109,
      "type": "community",
      "effect": {
        "action": "pay",
        "amount": 50
      }
    },
    {
      "id": 110,
      "type": "community",
      "effect": {
        "action": "pay",
        "amount": 25
      }
    }
  ],
  "freeParkingPot": 0,
  "dice": null,
  "doublesCount": 0,
  "lastMoveSteps": null,
  "eventLog": [
    {
      "key": "event.monopolyRent",
      "params": {
        "owner": "Alpha",
        "name": "Bravo"
      }
    }
  ],
  "pendingAction": {
    "type": "payRent",
    "spaceId": 39,
    "amount": 100
  },
  "justBoughtSpaceId": null,
  "builtThisStop": false,
  "reconnectGrace": null,
  "pendingTrades": [],
  "nextTradeId": 0,
  "tradesEnabled": false
}
