import { writeFileSync } from 'node:fs';
import { createSeededState } from '../src/logic/seed';
import { GamePhase, LogEventKey, PendingActionType } from '../src/types/game';

const BOARDWALK = 39; // id 39: rent[0] === 50, color #00008B
const PARK_PLACE = 37; // id 37: color #00008B (same Dark Blue group)

const state = createSeededState({
  players: [
    { id: 0, name: 'Alpha', money: 1000, passedGo: true },
    { id: 1, name: 'Bravo', money: 1500, passedGo: true },
  ],
  board: {
    [PARK_PLACE]: { owner: 0 },
    [BOARDWALK]: { owner: 0 },
  },
  currentPlayer: 1,
  turnOrder: [1, 0],
  phase: GamePhase.Resolving,
  pendingAction: {
    type: PendingActionType.PayRent,
    spaceId: BOARDWALK,
    amount: 50 * 2, // base rent doubled by the full color group
  },
  tradesEnabled: false,
});

// Seed the doubling message so the log explains why the rent is doubled.
state.eventLog = [
  { key: LogEventKey.MonopolyRent, params: { owner: 'Alpha', name: 'Bravo' } },
];

const out =
  "import type { GameState } from '../../src/types/game'\n" +
  '\n' +
  '// GENERATED by `npm run print-monopoly-rent-seed` — do not edit by hand.\n' +
  '// Alpha owns the full Dark Blue set (37 + 39); Bravo owes $100 on Boardwalk (base $50 x2).\n' +
  `export const monopolyRentSeed: GameState = ${JSON.stringify(state, null, 2)}\n`;

writeFileSync('e2e/fixtures/monopoly-rent-seed.ts', out);
console.log('wrote e2e/fixtures/monopoly-rent-seed.ts');