import { writeFileSync } from 'node:fs';
import { createSeededState } from '../src/logic/seed';
import { GamePhase } from '../src/types/game';

const SALVADOR = 1; // id 1: price 60
const RIO = 3; // id 3: price 60
const TLV_AIRPORT = 5; // id 5: railroad, price 200
const TEL_AVIV = 6; // id 6: price 100
const JERUSALEM = 9; // id 9: price 120

const tradeState = createSeededState({
  players: [
    { id: 0, name: 'Alpha', money: 1200 },
    { id: 1, name: 'Bravo', money: 1200 },
  ],
  board: {
    [SALVADOR]: { owner: 0 },
    [RIO]: { owner: 0 },
    [TLV_AIRPORT]: { owner: 0 },
    [TEL_AVIV]: { owner: 1 },
    [JERUSALEM]: { owner: 1 },
  },
  currentPlayer: 0,
  turnOrder: [0, 1],
  phase: GamePhase.Waiting,
  tradesEnabled: true,
});

const botState = createSeededState({
  players: [
    { id: 0, name: 'Alpha', money: 1200 },
    { id: 1, name: 'Droid', money: 1200, isBot: true },
  ],
  board: {
    [SALVADOR]: { owner: 0 },
    [RIO]: { owner: 0 },
    [TLV_AIRPORT]: { owner: 0 },
    [TEL_AVIV]: { owner: 1 },
  },
  currentPlayer: 0,
  turnOrder: [0, 1],
  phase: GamePhase.Waiting,
  tradesEnabled: true,
});

const cashState = createSeededState({
  players: [
    { id: 0, name: 'Alpha', money: 1200 },
    { id: 1, name: 'Bravo', money: 50 },
  ],
  board: {
    [SALVADOR]: { owner: 0 },
    [RIO]: { owner: 0 },
    [TLV_AIRPORT]: { owner: 0 },
    [TEL_AVIV]: { owner: 1 },
    [JERUSALEM]: { owner: 1 },
  },
  currentPlayer: 0,
  turnOrder: [0, 1],
  phase: GamePhase.Waiting,
  tradesEnabled: true,
});

const header = (comment: string) =>
  "import type { GameState } from '../../src/types/game'\n" +
  '\n' +
  '// GENERATED by `npm run print-trade-seed` — do not edit by hand.\n' +
  `// ${comment}\n`;

writeFileSync(
  'e2e/fixtures/trade-seed.ts',
  header('Alpha (current, $1200) owns Salvador/Rio/TLV Airport; Bravo ($1200) owns Tel Aviv/Jerusalem.') +
    `export const tradeSeed: GameState = ${JSON.stringify(tradeState, null, 2)}\n`,
);
writeFileSync(
  'e2e/fixtures/trade-bot-seed.ts',
  header('Alpha (current, $1200) owns Salvador/Rio/TLV Airport; bot Droid ($1200) owns Tel Aviv.') +
    `export const tradeBotSeed: GameState = ${JSON.stringify(botState, null, 2)}\n`,
);
writeFileSync(
  'e2e/fixtures/trade-cash-seed.ts',
  header('Alpha (current, $1200) owns Salvador/Rio/TLV Airport; Bravo ($50) owns Tel Aviv/Jerusalem.') +
    `export const tradeCashSeed: GameState = ${JSON.stringify(cashState, null, 2)}\n`,
);
console.log('wrote e2e/fixtures/trade-seed.ts, e2e/fixtures/trade-bot-seed.ts and e2e/fixtures/trade-cash-seed.ts');
