import { writeFileSync } from 'node:fs'
import { createSeededState } from '../src/logic/seed'
import { GamePhase, PendingActionType } from '../src/types/game'

const BOARDWALK = 39 // id 39: rent[4] === 1700, houseCost [100, 200, 300, 400, 500]
const MEDITERRANEAN = 3 // id 3: price 60, houseCost[0] === 25
const READING_RAILROAD = 5 // id 5: price 200
const ELECTRIC_COMPANY = 12 // id 12: price 150

const state = createSeededState({
  players: [
    { id: 0, name: 'Alpha', money: 1000, passedGo: true },
    { id: 1, name: 'Bravo', money: 50, passedGo: true },
  ],
  board: {
    [BOARDWALK]: { owner: 0, houses: 4 },
    [MEDITERRANEAN]: { owner: 1, houses: 1 },
    [READING_RAILROAD]: { owner: 1 },
    [ELECTRIC_COMPANY]: { owner: 1 },
  },
  currentPlayer: 1,
  turnOrder: [1, 0],
  phase: GamePhase.Resolving,
  pendingAction: {
    type: PendingActionType.PayRent,
    spaceId: BOARDWALK,
    amount: 1700,
  },
  tradesEnabled: false,
})

// Expected liquidation (the reducer is the source of truth; this documents it):
//   cash: 50
//   Mediterranean (1 house): floor(25 * 0.75) + floor(60 * 0.75) = 18 + 45 = 63
//   Reading Railroad: floor(200 * 0.75) = 150
//   Electric Company: floor(150 * 0.75) = 112
//   total = 50 + 63 + 150 + 112 = 375
// Alpha ends with 1000 + 375 = 1375. The properties return to the bank.

const out =
  "import type { GameState } from '../../src/types/game'\n" +
  '\n' +
  '// GENERATED by `npm run print-bankruptcy-liquidation-seed` — do not edit by hand.\n' +
  '// Bravo is at the rent prompt ($1700 on Alpha Boardwalk); Bravo has $50 + 3 properties\n' +
  '// (Mediterranean 1 house, Reading RR, Electric Co.) liquidated for $375 cash to Alpha.\n' +
  `export const bankruptcyLiquidationSeed: GameState = ${JSON.stringify(state, null, 2)}\n`

writeFileSync('e2e/fixtures/bankruptcy-liquidation-seed.ts', out)
console.log('wrote e2e/fixtures/bankruptcy-liquidation-seed.ts')
console.log('JSON for manual pasting:')
console.log(JSON.stringify(state))
