import { writeFileSync } from 'node:fs';
import { createSeededState } from '../src/logic/seed';

const base = createSeededState({ players: [], currentPlayer: 0 });

const out =
  "import type { Card, Space } from '../../src/types/game'\n" +
  '\n' +
  '// GENERATED by `npm run print-initial-state` — do not edit by hand.\n' +
  `export const INITIAL_BOARD: Space[] = ${JSON.stringify(base.board, null, 2)}\n\n` +
  `export const INITIAL_CHANCE_DECK: Card[] = ${JSON.stringify(base.chanceDeck, null, 2)}\n\n` +
  `export const INITIAL_COMMUNITY_DECK: Card[] = ${JSON.stringify(base.communityDeck, null, 2)}\n`;

writeFileSync('e2e/fixtures/initial-state.ts', out);
console.log('wrote e2e/fixtures/initial-state.ts');