import { writeFileSync } from 'node:fs'
import { createSeededState } from '../src/logic/seed'
import { GamePhase, PendingActionType } from '../src/types/game'

const state = createSeededState({
  players: [
    { id: 0, name: 'Alpha', money: 1000, passedGo: true },
    { id: 1, name: 'Bravo', money: 1, passedGo: true },
  ],
  board: {
    39: { owner: 0, houses: 4 },
    11: { owner: 0 },
    28: { owner: 0 },
  },
  currentPlayer: 1,
  turnOrder: [1, 0],
  phase: GamePhase.Resolving,
  pendingAction: { type: PendingActionType.PayRent, spaceId: 39, amount: 1700 },
  tradesEnabled: false,
})

const out =
  "import type { GameState } from '../../src/types/game'\n" +
  '\n' +
  '// GENERATED by `npm run print-seed` — do not edit by hand.\n' +
  '// Boardwalk (39) owned by Alpha with 4 houses; Bravo owes $1700 and has $1.\n' +
  `export const bankruptcySeed: GameState = ${JSON.stringify(state, null, 2)}\n`

writeFileSync('e2e/fixtures/bankruptcy-seed.ts', out)
console.log('wrote e2e/fixtures/bankruptcy-seed.ts')
console.log('JSON for manual pasting:')
console.log(JSON.stringify(state))